### PR TITLE
Leaderboard Action

### PR DESCRIPTION
**Pull request by DivyanshIsProAsf**
--------------------------------------------------------------------------------

- This is a...
  - [x] Actionpack    
  - [ ] Action
  - [ ] Function
- [x] I have followed the Guidelines for Contributing as closely as possible.
- [x] I have thoroughly tested my action(pack) or function and ensured that it works properly, even when used incorrectly.
- [x] This is not just a wrapper/alias for another command - it has an actual use.

### CODE REVIEW

**Review by DracoClaw — CHANGES_REQUESTED** [review]
- change the name of `/leaderboard` as it is disabling the native Levels plugin command
- error handling if {$donos} is empty and the `/leaderboard` command is run L:17
- when running the `/editpoint` command i am getting an error saying you must provide an array for `{push}` L:14
- you are setting {=data} and then right away setting {=donos}

**Comment by DivyanshIsProAsf** [comment]
This should be ready. Any questions can be DMed to Divyansh#6868!

**Comment by DivyanshIsProAsf** [comment]
Finished

**Comment by DivyanshIsProAsf** [comment]
Fixed some bugs

**Comment by DivyanshIsProAsf** [comment]
Updated

**Comment by DivyanshIsProAsf** [comment]
hi

**Comment by DivyanshIsProAsf** [comment]
ee

**Pull request merged**
